# -*- coding: utf-8 -*-
"""Procesamiento

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/109xZFfQOI8e3jGZRvFIJQgw25VnMhgan
"""

# 0. Install dependencies
!pip install ultralytics opencv-python matplotlib

"""### Step 1, 2, 3 & 4: Image Processing
We will load the image, apply a Gaussian blur for smoothing, and use Canny for edge detection.
"""

import cv2
import numpy as np
from matplotlib import pyplot as plt
import requests
from PIL import Image
from io import BytesIO



def process_image(img_path):
    img = cv2.imread(img_path)
    if img is None:
        print("Error: Could not load image. Please check the path.")
        return

    img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    # 2. Gaussian Blur
    img_smooth = cv2.GaussianBlur(img_rgb, (5, 5), 0)

    # 3. Canny Edge Detection
    img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    edges = cv2.Canny(img_gray, 100, 200)

    # 4. Visualization
    plt.figure(figsize=(15, 5))
    plt.subplot(131), plt.imshow(img_rgb), plt.title('Original')
    plt.subplot(132), plt.imshow(img_smooth), plt.title('Suavizada (Gaussian)')
    plt.subplot(133), plt.imshow(edges, cmap='gray'), plt.title('Bordes (Canny)')
    plt.show()

    return img_rgb


img_rgb = process_image('image.jpg')

"""### Step 5 & 6: YOLO Detection
We will use a pre-trained YOLOv8 model to detect objects.
"""

from ultralytics import YOLO

# Load pre-trained model
model = YOLO('yolov8n.pt')

# Run detection
def detect_objects(img_path):
    results = model(img_path)

    # Show results
    for r in results:
        im_array = r.plot()  # plot a BGR numpy array of predictions
        im_rgb = cv2.cvtColor(im_array, cv2.COLOR_BGR2RGB)
        plt.figure(figsize=(10, 10))
        plt.imshow(im_rgb)
        plt.axis('off')
        plt.title('YOLOv8 Detection')
        plt.show()


detect_objects('image.jpg')

"""### Step 7: Run the full pipeline
We download a sample image to demonstrate the processing and detection functions.
"""

import os

# 1. Use the image uploaded by the user
img_path = 'image.jpg'

if not os.path.exists(img_path):
    print(f"Error: {img_path} not found. Please ensure you have uploaded the file to the sidebar.")
else:
    # Execute Step 1-4: Processing and visualization
    print("Processing image filters...")
    process_image(img_path)

    # Execute Step 5-6: YOLOv8 Detection
    print("Running YOLOv8 detection...")
    detect_objects(img_path)