# -*- coding: utf-8 -*-
"""convolucion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mc-Gjcuskr8IKzSvOxEnu6iyGWKxk9EM
"""

import matplotlib.pyplot as plt
import os

# Create directory structure
os.makedirs('ejercicio_3_convolucion_1d/graficos', exist_ok=True)

def convolution_1d(signal, kernel):
    n = len(signal)
    m = len(kernel)
    # The length of the full convolution is n + m - 1
    result = [0] * (n + m - 1)

    for i in range(len(result)):
        for j in range(m):
            if 0 <= i - j < n:
                result[i] += signal[i - j] * kernel[j]
    return result

# 1. Define input signal (15 values)
signal = [1, 2, 3, 4, 5, 4, 3, 2, 1, 0, 1, 2, 3, 2, 1]

# 2. Define kernel (Moving average filter)
kernel = [1/3, 1/3, 1/3]

# 3. Implement convolution
result = convolution_1d(signal, kernel)

# 4. Plot and Save
# Plot Signal
plt.figure(figsize=(10, 4))
plt.stem(range(len(signal)), signal)
plt.title('Señal Original')
plt.grid(True)
plt.savefig('ejercicio_3_convolucion_1d/graficos/señal_original.png')
plt.show()

# Plot Kernel
plt.figure(figsize=(10, 4))
plt.stem(range(len(kernel)), kernel)
plt.title('Kernel')
plt.grid(True)
plt.savefig('ejercicio_3_convolucion_1d/graficos/kernel.png')
plt.show()

# Plot Result
plt.figure(figsize=(10, 4))
plt.stem(range(len(result)), result)
plt.title('Resultado de la Convolución')
plt.grid(True)
plt.savefig('ejercicio_3_convolucion_1d/graficos/resultado.png')
plt.show()

# Create README.md
with open('ejercicio_3_convolucion_1d/README.md', 'w') as f:
    f.write('# Ejercicio 3: Convolución 1D\nImplementación manual de convolución en Python.')

print("Archivos guardados en: ejercicio_3_convolucion_1d/")